version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  versioning-strategy: increase
  ignore:
  - dependency-name: webpack
    versions:
    - 5.34.0
  - dependency-name: "@plusnew/driver-dom"
    versions:
    - 1.3.2
    - 1.4.0
  - dependency-name: webpack-cli
    versions:
    - 4.4.0
    - 4.5.0
  - dependency-name: "@plusnew/core"
    versions:
    - 1.6.2
